# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.php'
      - '**.txt'
      - '**.json'
      - 'composer.*'
  push:
    paths:
      - '**.php'
      - '**.txt'
      - '**.json'
      - 'composer.*'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1, 8.2]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, json, libxml, mbstring, pcre, reflection, spl, xml, xmlwriter
          coverage: none
          ini-values: assert.exception=1, zend.assertions=1

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test
